# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image:  php:5.6-zts

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: 
          name: Intalling OS essentials
          command: |
            apt-get update && apt-get install -y git zip unzip build-essential
      - run:
          name: Installing composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php composer-setup.php --install-dir=/usr/local/bin --filename=composer
            php -r "unlink('composer-setup.php');"

      - run:
          name: Installing PHP dependencies
          command: |
            pecl install pthreads-2.0.10 && docker-php-ext-enable pthreads
            pecl install xdebug-2.5.5 && docker-php-ext-enable xdebug
      
      - save_cache:
          paths:
            - vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: 
          name: Installing project dependencies
          command: |
            composer install

      - run: 
          name: Run tests
          command: |
            cat .circleci/thread.ascii && vendor/bin/codecept run --coverage --coverage-html

      - store_artifacts:
          path: ./tests/_output/coverage
          destination: coverage

